- name: ":desktop_computer: compatibility"
  color: "#b32099"
  description: "Environment adaption"
- name: ":blue_book: doc-doxygen"
  color: "#ceb48c"
  description: "Doxygen-built APIs"
- name: ":bricks: infrastructure"
  color: "#c3a3f5"
  description: "Dependencies & architecture change"
- name: ":bug: bug"
  color: "#d73a4a"
  description: "Something isn't working"
- name: ":globe_with_meridians: doc-translation"
  color: "#40d295"
  description: "Documentation internationalization"
- name: ":notebook: doc-sphinx"
  color: "#89b365"
  description: "Sphinx-built tutorials"
- name: ":package: assets"
  color: "#f18971"
  description: "Compiled products"
- name: ":page_with_curl: publication"
  color: "#6ca8ec"
  description: "Paper or patent related"
- name: ":recycle: refactor"
  color: "#5e2f61"
  description: "Code refactor"
- name: ":sparkles: feature"
  color: "#a2eeef"
  description: "Support new features"
- name: ":test_tube: tests"
  color: "#cfd3d7"
  description: "Package-level tests"
- name: ":zap: performance"
  color: "#6bd8ad"
  description: "Performance improvement"